[theme]
# Primary color for interactive elements.
primaryColor = "#586e75"

# Background color for the main content area.
backgroundColor = "#2C3E50"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#586e75"

# Color used for almost all text
textColor = "#F1F4F8"

[server]
headless = true
